components-ai/css.gui

- .changeset/config.json
- .changeset/three-hats-love.md
- apps/docs/components/examples/Fieldset.tsx
- packages/gui/src/components/Editor/Fieldset.tsx
> Allow for nested fieldsets

- .changeset/silly-goats-fetch.md
- packages/gui/src/data/properties.ts
> Add border style input

- .changeset/tiny-buses-unite.md
- apps/docs/components/Sidebar.tsx
- apps/docs/components/examples/Demo.tsx
- apps/docs/pages/exports/css.mdx
- packages/gui/src/lib/codegen/index.ts
- packages/gui/src/lib/codegen/stringify-css-object.ts
- packages/gui/src/lib/codegen/to-css-object.ts
- packages/gui/src/lib/elements.ts
- packages/gui/src/lib/index.ts
- packages/gui/src/lib/util.ts
> Add basic CSS codegen

- .changeset/mighty-keys-mix.md
- apps/docs/components/examples/Demo.tsx
- apps/docs/components/examples/Fieldset.tsx
- apps/docs/components/examples/FontFamily.tsx
- apps/docs/pages/components/editor.mdx
- apps/docs/pages/components/fieldset.mdx
- apps/docs/pages/examples/border-images.tsx
- apps/docs/pages/examples/filters.tsx
- apps/docs/pages/examples/shadows.tsx
- apps/docs/pages/examples/transforms.tsx
- apps/docs/pages/examples/transitions.tsx
- apps/docs/pages/exports/css.mdx
- apps/docs/pages/getting-started.mdx
- apps/docs/pages/inputs/font-family.mdx
- apps/docs/pages/introduction.mdx
- packages/gui/src/components/RenderElement.tsx
- packages/gui/src/components/Styled.tsx
- packages/gui/src/index.ts
- readme.md
> Use a styled component with built-in tag names to render elements

- .changeset/honest-carpets-check.md
- apps/docs/components/Sidebar.tsx
- apps/docs/pages/examples/borders.tsx
- packages/gui/src/data/properties.ts
> Add directional borders

- .changeset/rich-meals-drive.md
- packages/gui/src/components/inputs/ColorInput.tsx
- packages/gui/src/components/primitives/ColorPicker/Popover.tsx
> Place color picker label on the top

- packages/gui/src/data/css-properties.ts
* filter out duplicate CSS properties
* filter out modules that are completely unsupported (like speech)
> Better count of unsupported props

- .changeset/young-pugs-press.md
- packages/gui/src/components/inputs/FontFamily/Input.tsx
- packages/gui/src/data/properties.ts
> Add support for roboto flex, fix width handling for variable fonts

- .changeset/three-teachers-fetch.md
- packages/gui/src/components/inputs/FontFamily/Input.tsx
> Fix controls for some variable font settings

- .changeset/gold-ducks-grab.md
- apps/docs/components/examples/Responsive.tsx
- apps/docs/pages/inputs/responsive.mdx
- packages/gui/src/components/Editor/Controls.tsx
- packages/gui/src/components/Responsive/Input.tsx
- packages/gui/src/data/properties.ts
- packages/gui/src/lib/constants.ts
> Add responsive keywords

- .changeset/fast-countries-retire.md
- packages/gui/src/components/inputs/FontFamily/Input.tsx
> Add display fonts

- .changeset/angry-hounds-return.md
- packages/gui/src/data/properties.ts
> Make some flex inputs responsive

- .changeset/sixty-months-deny.md
- packages/gui/src/components/inputs/FontFamily/Input.tsx
> Add handwriting fonts

- .changeset/khaki-walls-rescue.md
- apps/docs/components/Header.tsx
- apps/docs/components/playground/Canvas.tsx
- apps/docs/components/playground/Layout.tsx
- apps/docs/components/playground/Sidebar.tsx
- apps/docs/components/playground/types.ts
- apps/docs/pages/_app.tsx
- apps/docs/pages/playground.tsx
- packages/gui/src/components/inputs/TextInput.tsx
- packages/gui/src/index.ts
Visually build and style an HTML element.
https://user-images.githubusercontent.com/1424573/169357972-ba2e2afb-0a4c-43ec-92c1-dd3bd67ca29e.mp4
> CSS GUI playground

- .changeset/great-chefs-occur.md
- apps/docs/components/examples/FontFamily.tsx
- packages/gui/src/components/AddProperty.tsx
- packages/gui/src/components/Editor/Controls.tsx
- packages/gui/src/components/providers/DynamicPropertiesContext.tsx
- packages/gui/src/components/providers/EditorContext.tsx
> Dynamic children

- .changeset/cool-stingrays-visit.md
- packages/gui/src/components/AddProperty.tsx
Desired behavior is that after you add a property the combo box is empty. Want to make sure I"m not missing any unintended side effects by removing this.
> Clears the combobox value after you add a property

- .changeset/nice-keys-prove.md
- packages/gui/src/components/AddProperty.tsx
- packages/gui/src/components/html/AttributeEditor.tsx
- packages/gui/src/components/primitives/Combobox.tsx
In most cases I think we want to clear the combobox, but in the case of selecting the tag type we probably want to keep that displayed. So because of that I've made the clear an option
> Clear combobox.. sometimes

- packages/gui/src/components/primitives/Number/Input.tsx
Make number inputs fit to the width of the content so it's more compact.
> compact number inputs

- .changeset/cuddly-books-sing.md
- packages/gui/src/components/html/Renderer.tsx
> Rename class to className

- .changeset/blue-ears-bake.md
- packages/gui/src/components/primitives/Number/Input.tsx
Fixed DraggableInput to be immediately reflected value when keyed down.
https://user-images.githubusercontent.com/56961325/170867461-2bf14cfe-ffe2-4470-abec-bce05814de04.mov
https://user-images.githubusercontent.com/56961325/170867529-c1978f7e-cfac-489b-a6a9-c38f4255e38c.mov
> Reflected at keydown immediately

- .changeset/gorgeous-planets-rush.md
- packages/gui/src/components/primitives/Number/Input.tsx
- packages/gui/src/lib/theme.ts
Fixes
* importing a theme now attempts to parse a number and value
* Can no longer key down/up out of range of theme values
> Fix Theme import and ranges

- .changeset/shaggy-starfishes-pull.md
- packages/gui/src/components/AddFieldset.tsx
- packages/gui/src/components/Editor/Controls.tsx
> Implement dynamic fieldsets for pseudos

- .changeset/shaggy-pets-hear.md
- packages/gui/package.json
- packages/gui/src/components/AddProperty.tsx
- packages/gui/src/components/html/editor.tsx
- yarn.lock
> kebab case properties

- .changeset/tough-crews-warn.md
- packages/gui/src/components/primitives/Number/Input.tsx
> Allow users to manually input decimals into number input

- .changeset/green-taxis-grab.md
- .changeset/neat-impalas-deliver.md
- packages/gui/package.json
- packages/gui/src/components/html/Export.tsx
- packages/gui/src/components/html/editor.tsx
- packages/gui/src/useCopyToClipboard.ts
- yarn.lock
> Add tabs for node/tree/export, add copy to clipboard

- packages/gui/src/lib/transformers/styles-to-editor-schema.ts
> Fix parsing of keyword values in arrays

- .changeset/orange-lamps-play.md
- packages/gui/src/components/html/editor.tsx
> Always show "add child" button

- .changeset/seven-dolphins-sit.md
- packages/gui/src/components/Editor/Controls.tsx
- packages/gui/src/components/providers/EditorContext.tsx
- packages/gui/src/components/ui/dropdowns/EditorDropdown.tsx
- packages/gui/src/components/ui/dropdowns/FieldsetDropdown.tsx
- packages/gui/src/components/ui/dropdowns/styles.ts
> Clear all styles

- .changeset/tender-keys-switch.md
- packages/gui/src/components/AddFieldset.tsx
- packages/gui/src/components/AddProperty.tsx
> Improve comboboxes

- packages/gui/jest.config.cjs
- packages/gui/package.json
- packages/gui/src/components/schemas/columns.tsx
- packages/gui/src/lib/parse.test.ts
- packages/gui/src/lib/parse.ts
- packages/gui/tsconfig.json
- yarn.lock
Function to tokenize CSS input into string tokens that can be picked up and parsed by our schemas. Also set up Jest and write some tests to ensure everything parses correctly. (@johno can you check and make sure I did everything right?)
> Tokenization function and tests

- .changeset/flat-dots-lie.md
- apps/docs/data/initial-html-editor-data.ts
- packages/gui/src/components/html/ComponentEditor.tsx
- packages/gui/src/components/html/Renderer.tsx
> Component attribute editor

- .changeset/poor-rules-train.md
- packages/gui/src/components/html/Renderer.tsx
- packages/gui/src/components/html/TreeNode.tsx
- packages/gui/src/lib/codegen/util.ts
- packages/gui/src/lib/transformers/editor-schema-to-hast.ts
- packages/gui/src/lib/transformers/plugins/convert-components-to-hast.ts
> Component children

- .changeset/khaki-poets-own.md
- packages/gui/src/components/html/CanvasProvider.tsx
- packages/gui/src/components/html/Renderer/Element.tsx
- packages/gui/src/components/html/Renderer/Html.tsx
- packages/gui/src/components/html/Renderer/Text.tsx
- packages/gui/src/components/html/util.ts
> Enable selection for nested components

- .changeset/stupid-laws-brake.md
- packages/gui/src/lib/transformers/hast-to-editor-schema.ts
- packages/gui/src/lib/transformers/plugins/transform-style-attributes.ts
> Drop style attributes during import for now

- .changeset/cold-kids-refuse.md
- packages/gui/src/lib/codegen/emotion.ts
- packages/gui/src/lib/codegen/enhance-sfc.ts
- packages/gui/src/lib/codegen/html.ts
- packages/gui/src/lib/codegen/react.ts
- packages/gui/src/lib/codegen/styled-jsx.ts
- packages/gui/src/lib/codegen/theme-ui.ts
- packages/gui/src/lib/codegen/to-css-object.ts
- packages/gui/src/lib/codegen/types.ts
- packages/gui/src/lib/codegen/vue.ts
> Make sure all code generators are passed theme in export

- .changeset/strong-cheetahs-tap.md
- packages/gui/src/lib/codegen/stringify-css-object.ts
- packages/gui/src/lib/codegen/stringify-hast-node-as-html.ts
- packages/gui/src/lib/codegen/util.ts
Related to #616 and #617
Note: The style string will be replaced with a style element and proper CSS string in a PR later today.
> Use a style string rather than object

- .changeset/long-camels-study.md
- packages/gui/package.json
- packages/gui/src/lib/codegen/enhance-sfc.ts
- packages/gui/src/lib/transformers/editor-schema-to-hast.ts
- packages/gui/src/lib/transformers/inline-styles-to-style-element.ts
- yarn.lock
> Add style element to enhance export
